### ISSUE TITLE
LangBeim Aufruf des Projekts aus VS10 heraus und dem Test Tritt beim Wiederverbinden im Errorlog immer der folgende Fehler auf:

### ISSUE THREAD

**Issue by ez5393ez** [TheCrazyT/DSO_Economic#6]
Beim Aufruf des Projekts aus VS10 heraus und dem Test Tritt beim Wiederverbinden im Errorlog immer der folgende Fehler auf:
"Eine Ausnahme (erste Chance) des Typs "System.IO.EndOfStreamException" ist in mscorlib.dll aufgetreten."

Edit von TheCrazyT:
Gehört eigendlich nicht mit zu diesem Bug, aber ich lass es mal hier drin, da ich deinen Beitrag nicht verschieben kann ;)
Beim nächsten mal bitte nen separates Thema, sonst verlier ich den Überblick, wenn noch mehr Leute hier posten.

_Originally posted by @XRyu in https://github.com/TheCrazyT/DSO_Economic/issues/3#issuecomment-1138715_

**Comment by TheCrazyT** [comment]
@ez5393ez das Projekt ist mittlerweile steinalt.

Mittlerweile wird mit sicherheit auch kein flash mehr eingesetzt.
(Und damit würde das ganze eh nicht mehr funktionieren)

Ich werde das Projekt mal archivieren.

**Comment by TheCrazyT** [comment]
Meine Vermutung mit Flash(obwohl das eigentlich schon tot sein sollte!) war wohl falsch.
Ich verschieb das mit der Archivierung erstmal und schau mir das Ganze mal an wenn ich Zeit finde.

**Comment by TheCrazyT** [comment]
@ez5393ez bist du ein bot?
